# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RCDataBase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'FMDB', '~> 2.7.5'
  # Pods for RCDataBase

  target 'RCDataBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RCDataBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
